<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use App\Models\Countrie;
class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ["code"=> "AD","name"=> "أندورا"],
            ["code"=> "AE","name"=> "الامارات العربية المتحدة"],
            ["code"=> "AF","name"=> "أفغانستان"],
            ["code"=> "AG","name"=> "أنتيجوا وبربودا"],
            ["code"=> "AI","name"=> "أنجويلا"],
            ["code"=> "AL","name"=> "ألبانيا"],
            ["code"=> "AM","name"=> "أرمينيا"],
            ["code"=> "AO","name"=> "أنجولا"],
            ["code"=> "AQ","name"=> "القطب الجنوبي"],
            ["code"=> "AR","name"=> "الأرجنتين"],
            ["code"=> "AS","name"=> "ساموا الأمريكية"],
            ["code"=> "AT","name"=> "النمسا"],
            ["code"=> "AU","name"=> "أستراليا"],
            ["code"=> "AW","name"=> "آروبا"],
            ["code"=> "AX","name"=> "جزر أولان"],
            ["code"=> "AZ","name"=> "أذربيجان"],
            ["code"=> "BA","name"=> "البوسنة والهرسك"],
            ["code"=> "BB","name"=> "بربادوس"],
            ["code"=> "BD","name"=> "بنجلاديش"],
            ["code"=> "BE","name"=> "بلجيكا"],
            ["code"=> "BF","name"=> "بوركينا فاسو"],
            ["code"=> "BG","name"=> "بلغاريا"],
            ["code"=> "BH","name"=> "البحرين"],
            ["code"=> "BI","name"=> "بوروندي"],
            ["code"=> "BJ","name"=> "بنين"],
            ["code"=> "BL","name"=> "سان بارتيلمي"],
            ["code"=> "BM","name"=> "برمودا"],
            ["code"=> "BN","name"=> "بروناي"],
            ["code"=> "BO","name"=> "بوليفيا"],
            ["code"=> "BQ","name"=> "بونير"],
            ["code"=> "BR","name"=> "البرازيل"],
            ["code"=> "BS","name"=> "الباهاما"],
            ["code"=> "BT","name"=> "بوتان"],
            ["code"=> "BV","name"=> "جزيرة بوفيه"],
            ["code"=> "BW","name"=> "بتسوانا"],
            ["code"=> "BY","name"=> "روسيا البيضاء"],
            ["code"=> "BZ","name"=> "بليز"],
            ["code"=> "CA","name"=> "كندا"],
            ["code"=> "CC","name"=> "جزر كوكوس"],
            ["code"=> "CD","name"=> "جمهورية الكونغو الديمقراطية"],
            ["code"=> "CF","name"=> "جمهورية افريقيا الوسطى"],
            ["code"=> "CG","name"=> "الكونغو - برازافيل"],
            ["code"=> "CH","name"=> "سويسرا"],
            ["code"=> "CI","name"=> "ساحل العاج"],
            ["code"=> "CK","name"=> "جزر كوك"],
            ["code"=> "CL","name"=> "شيلي"],
            ["code"=> "CM","name"=> "الكاميرون"],
            ["code"=> "CN","name"=> "الصين"],
            ["code"=> "CO","name"=> "كولومبيا"],
            ["code"=> "CR","name"=> "كوستاريكا"],
            ["code"=> "CU","name"=> "كوبا"],
            ["code"=> "CV","name"=> "الرأس الأخضر"],
            ["code"=> "CW","name"=> "كوراساو"],
            ["code"=> "CX","name"=> "جزيرة الكريسماس"],
            ["code"=> "CY","name"=> "قبرص"],
            ["code"=> "CZ","name"=> "جمهورية التشيك"],
            ["code"=> "DE","name"=> "ألمانيا"],
            ["code"=> "DJ","name"=> "جيبوتي"],
            ["code"=> "DK","name"=> "الدانمرك"],
            ["code"=> "DM","name"=> "دومينيكا"],
            ["code"=> "DO","name"=> "جمهورية الدومينيك"],
            ["code"=> "DZ","name"=> "الجزائر"],
            ["code"=> "EC","name"=> "الاكوادور"],
            ["code"=> "EE","name"=> "استونيا"],
            ["code"=> "EG","name"=> "مصر"],
            ["code"=> "EH","name"=> "الصحراء الغربية"],
            ["code"=> "ER","name"=> "اريتريا"],
            ["code"=> "ES","name"=> "أسبانيا"],
            ["code"=> "ET","name"=> "اثيوبيا"],
            ["code"=> "FI","name"=> "فنلندا"],
            ["code"=> "FJ","name"=> "فيجي"],
            ["code"=> "FK","name"=> "جزر فوكلاند"],
            ["code"=> "FM","name"=> "ميكرونيزيا"],
            ["code"=> "FO","name"=> "جزر فارو"],
            ["code"=> "FR","name"=> "فرنسا"],
            ["code"=> "GA","name"=> "الجابون"],
            ["code"=> "GB","name"=> "المملكة المتحدة"],
            ["code"=> "GD","name"=> "جرينادا"],
            ["code"=> "GE","name"=> "جورجيا"],
            ["code"=> "GF","name"=> "غويانا"],
            ["code"=> "GG","name"=> "غيرنزي"],
            ["code"=> "GH","name"=> "غانا"],
            ["code"=> "GI","name"=> "جبل طارق"],
            ["code"=> "GL","name"=> "جرينلاند"],
            ["code"=> "GM","name"=> "غامبيا"],
            ["code"=> "GN","name"=> "غينيا"],
            ["code"=> "GP","name"=> "جوادلوب"],
            ["code"=> "GQ","name"=> "غينيا الاستوائية"],
            ["code"=> "GR","name"=> "اليونان"],
            ["code"=> "GS","name"=> "جورجيا الجنوبية وجزر ساندويتش الجنوبية"],
            ["code"=> "GT","name"=> "جواتيمالا"],
            ["code"=> "GU","name"=> "جوام"],
            ["code"=> "GW","name"=> "غينيا بيساو"],
            ["code"=> "GY","name"=> "غيانا"],
            ["code"=> "HK","name"=> "هونج كونج الصينية"],
            ["code"=> "HM","name"=> "جزيرة هيرد وماكدونالد"],
            ["code"=> "HN","name"=> "هندوراس"],
            ["code"=> "HR","name"=> "كرواتيا"],
            ["code"=> "HT","name"=> "هايتي"],
            ["code"=> "HU","name"=> "المجر"],
            ["code"=> "ID","name"=> "اندونيسيا"],
            ["code"=> "IE","name"=> "أيرلندا"],
            ["code"=> "IL","name"=> "اسرائيل"],
            ["code"=> "IM","name"=> "جزيرة مان"],
            ["code"=> "IN","name"=> "الهند"],
            ["code"=> "IO","name"=> "المحيط الهندي البريطاني"],
            ["code"=> "IQ","name"=> "العراق"],
            ["code"=> "IR","name"=> "ايران"],
            ["code"=> "IS","name"=> "أيسلندا"],
            ["code"=> "IT","name"=> "ايطاليا"],
            ["code"=> "JE","name"=> "جيرسي"],
            ["code"=> "JM","name"=> "جامايكا"],
            ["code"=> "JO","name"=> "الأردن"],
            ["code"=> "JP","name"=> "اليابان"],
            ["code"=> "KE","name"=> "كينيا"],
            ["code"=> "KG","name"=> "قرغيزستان"],
            ["code"=> "KH","name"=> "كمبوديا"],
            ["code"=> "KI","name"=> "كيريباتي"],
            ["code"=> "KM","name"=> "جزر القمر"],
            ["code"=> "KN","name"=> "سانت كيتس ونيفيس"],
            ["code"=> "KP","name"=> "كوريا الشمالية"],
            ["code"=> "KR","name"=> "كوريا الجنوبية"],
            ["code"=> "KW","name"=> "الكويت"],
            ["code"=> "KY","name"=> "جزر الكايمن"],
            ["code"=> "KZ","name"=> "كازاخستان"],
            ["code"=> "LA","name"=> "لاوس"],
            ["code"=> "LB","name"=> "لبنان"],
            ["code"=> "LC","name"=> "سانت لوسيا"],
            ["code"=> "LI","name"=> "ليختنشتاين"],
            ["code"=> "LK","name"=> "سريلانكا"],
            ["code"=> "LR","name"=> "ليبيريا"],
            ["code"=> "LS","name"=> "ليسوتو"],
            ["code"=> "LT","name"=> "ليتوانيا"],
            ["code"=> "LU","name"=> "لوكسمبورج"],
            ["code"=> "LV","name"=> "لاتفيا"],
            ["code"=> "LY","name"=> "ليبيا"],
            ["code"=> "MA","name"=> "المغرب"],
            ["code"=> "MC","name"=> "موناكو"],
            ["code"=> "MD","name"=> "مولدافيا"],
            ["code"=> "ME","name"=> "الجبل الأسود"],
            ["code"=> "MF","name"=> "سانت مارتين"],
            ["code"=> "MG","name"=> "مدغشقر"],
            ["code"=> "MH","name"=> "جزر المارشال"],
            ["code"=> "MK","name"=> "مقدونيا"],
            ["code"=> "ML","name"=> "مالي"],
            ["code"=> "MM","name"=> "ميانمار"],
            ["code"=> "MN","name"=> "منغوليا"],
            ["code"=> "MO","name"=> "ماكاو الصينية"],
            ["code"=> "MP","name"=> "جزر ماريانا الشمالية"],
            ["code"=> "MQ","name"=> "مارتينيك"],
            ["code"=> "MR","name"=> "موريتانيا"],
            ["code"=> "MS","name"=> "مونتسرات"],
            ["code"=> "MT","name"=> "مالطا"],
            ["code"=> "MU","name"=> "موريشيوس"],
            ["code"=> "MV","name"=> "جزر الملديف"],
            ["code"=> "MW","name"=> "ملاوي"],
            ["code"=> "MX","name"=> "المكسيك"],
            ["code"=> "MY","name"=> "ماليزيا"],
            ["code"=> "MZ","name"=> "موزمبيق"],
            ["code"=> "NA","name"=> "ناميبيا"],
            ["code"=> "NC","name"=> "كاليدونيا الجديدة"],
            ["code"=> "NE","name"=> "النيجر"],
            ["code"=> "NF","name"=> "جزيرة نورفوك"],
            ["code"=> "NG","name"=> "نيجيريا"],
            ["code"=> "NI","name"=> "نيكاراجوا"],
            ["code"=> "NL","name"=> "هولندا"],
            ["code"=> "NO","name"=> "النرويج"],
            ["code"=> "NP","name"=> "نيبال"],
            ["code"=> "NR","name"=> "نورو"],
            ["code"=> "NU","name"=> "نيوي"],
            ["code"=> "NZ","name"=> "نيوزيلاندا"],
            ["code"=> "OM","name"=> "عمان"],
            ["code"=> "PA","name"=> "بنما"],
            ["code"=> "PE","name"=> "بيرو"],
            ["code"=> "PF","name"=> "بولينيزيا الفرنسية"],
            ["code"=> "PG","name"=> "بابوا غينيا الجديدة"],
            ["code"=> "PH","name"=> "الفيلبين"],
            ["code"=> "PK","name"=> "باكستان"],
            ["code"=> "PL","name"=> "بولندا"],
            ["code"=> "PM","name"=> "سانت بيير وميكولون"],
            ["code"=> "PN","name"=> "بتكايرن"],
            ["code"=> "PR","name"=> "بورتوريكو"],
            ["code"=> "PS","name"=> "فلسطين"],
            ["code"=> "PT","name"=> "البرتغال"],
            ["code"=> "PW","name"=> "بالاو"],
            ["code"=> "PY","name"=> "باراجواي"],
            ["code"=> "QA","name"=> "قطر"],
            ["code"=> "RE","name"=> "روينيون"],
            ["code"=> "RO","name"=> "رومانيا"],
            ["code"=> "RS","name"=> "صربيا"],
            ["code"=> "RU","name"=> "روسيا"],
            ["code"=> "RW","name"=> "رواندا"],
            ["code"=> "SA","name"=> "المملكة العربية السعودية"],
            ["code"=> "SB","name"=> "جزر سليمان"],
            ["code"=> "SC","name"=> "سيشل"],
            ["code"=> "SD","name"=> "السودان"],
            ["code"=> "SE","name"=> "السويد"],
            ["code"=> "SG","name"=> "سنغافورة"],
            ["code"=> "SH","name"=> "سانت هيلنا"],
            ["code"=> "SI","name"=> "سلوفينيا"],
            ["code"=> "SJ","name"=> "سفالبارد وجان مايان"],
            ["code"=> "SK","name"=> "سلوفاكيا"],
            ["code"=> "SL","name"=> "سيراليون"],
            ["code"=> "SM","name"=> "سان مارينو"],
            ["code"=> "SN","name"=> "السنغال"],
            ["code"=> "SO","name"=> "الصومال"],
            ["code"=> "SR","name"=> "سورينام"],
            ["code"=> "SS","name"=> "جنوب السودان"],
            ["code"=> "ST","name"=> "ساو تومي وبرينسيبي"],
            ["code"=> "SV","name"=> "السلفادور"],
            ["code"=> "SX","name"=> "سينت مارتن"],
            ["code"=> "SY","name"=> "سوريا"],
            ["code"=> "SZ","name"=> "سوازيلاند"],
            ["code"=> "TC","name"=> "جزر الترك وجايكوس"],
            ["code"=> "TD","name"=> "تشاد"],
            ["code"=> "TF","name"=> "المقاطعات الجنوبية الفرنسية"],
            ["code"=> "TG","name"=> "توجو"],
            ["code"=> "TH","name"=> "تايلند"],
            ["code"=> "TJ","name"=> "طاجكستان"],
            ["code"=> "TK","name"=> "توكيلو"],
            ["code"=> "TL","name"=> "تيمور الشرقية"],
            ["code"=> "TM","name"=> "تركمانستان"],
            ["code"=> "TN","name"=> "تونس"],
            ["code"=> "TO","name"=> "تونجا"],
            ["code"=> "TR","name"=> "تركيا"],
            ["code"=> "TT","name"=> "ترينيداد وتوباغو"],
            ["code"=> "TV","name"=> "توفالو"],
            ["code"=> "TW","name"=> "تايوان"],
            ["code"=> "TZ","name"=> "تانزانيا"],
            ["code"=> "UA","name"=> "أوكرانيا"],
            ["code"=> "UG","name"=> "أوغندا"],
            ["code"=> "UM","name"=> "جزر الولايات المتحدة البعيدة الصغيرة"],
            ["code"=> "US","name"=> "الولايات المتحدة الأمريكية"],
            ["code"=> "UY","name"=> "أورجواي"],
            ["code"=> "UZ","name"=> "أوزبكستان"],
            ["code"=> "VA","name"=> "الفاتيكان"],
            ["code"=> "VC","name"=> "سانت فنسنت وغرنادين"],
            ["code"=> "VE","name"=> "فنزويلا"],
            ["code"=> "VG","name"=> "جزر فرجين البريطانية"],
            ["code"=> "VI","name"=> "جزر فرجين الأمريكية"],
            ["code"=> "VN","name"=> "فيتنام"],
            ["code"=> "VU","name"=> "فانواتو"],
            ["code"=> "WF","name"=> "جزر والس وفوتونا"],
            ["code"=> "WS","name"=> "ساموا"],
            ["code"=> "XK","name"=> "كوسوفو"],
            ["code"=> "YE","name"=> "اليمن"],
            ["code"=> "YT","name"=> "مايوت"],
            ["code"=> "ZA","name"=> "جمهورية جنوب افريقيا"],
            ["code"=> "ZM","name"=> "زامبيا"],
            ["code"=> "ZW","name"=> "زيمبابوي"],
        ];

        foreach ($countries as $key => $country) {
            Countrie::create($country);
        }
    }
}
